# Generated by Django 5.0.7 on 2024-07-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(db_index=True, max_length=200, verbose_name='Имя')),
                ('lastname', models.CharField(db_index=True, max_length=200, verbose_name='Фамилия')),
                ('speciality', models.CharField(db_index=True, max_length=200, verbose_name='Специальность')),
                ('foto', models.ImageField(blank=True, upload_to='foto', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='ФИО владельца')),
                ('address', models.TextField(blank=True, db_index=True, max_length=200, verbose_name='Адрес')),
            ],
        ),
    ]
