# Generated by Django 5.0.7 on 2024-07-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='speciality',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название салона'),
        ),
    ]
