# Generated by Django 5.0.7 on 2024-07-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_alter_master_speciality_alter_salon_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='speciality',
        ),
    ]
