# Generated by Django 5.0.7 on 2024-07-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_remove_master_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='master',
            field=models.ManyToManyField(related_name='salons', to='salon.master', verbose_name='Салон'),
        ),
    ]
