# Generated by Django 5.0.7 on 2024-07-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_service_master_service_salon_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='service',
        ),
        migrations.AlterField(
            model_name='salon',
            name='master',
            field=models.ManyToManyField(blank=True, related_name='salons', to='salon.master', verbose_name='Салон'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='salons', to='salon.service', verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='master',
            name='service',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='masters', to='salon.service', verbose_name='Услуги'),
        ),
    ]
