# Generated by Django 5.0.7 on 2024-07-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_remove_master_service_alter_salon_master_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='service',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='master',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='service',
        ),
        migrations.AddField(
            model_name='master',
            name='master_salon',
            field=models.ManyToManyField(blank=True, related_name='master_salons', to='salon.salon', verbose_name='Салон'),
        ),
        migrations.AddField(
            model_name='master',
            name='master_service',
            field=models.ManyToManyField(blank=True, related_name='master_services', to='salon.service', verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='salon_service',
            field=models.ManyToManyField(blank=True, related_name='salon_services', to='salon.salon', verbose_name='Услуги салона'),
        ),
    ]
