# Generated by Django 5.0.7 on 2024-07-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0011_alter_feedback_options_alter_time_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('text', models.TextField(verbose_name='Текст рекламы')),
                ('responses', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество откликов')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Реклама',
            },
        ),
    ]
