# Generated by Django 5.0.7 on 2024-07-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0012_advertising'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='foto',
            field=models.ImageField(blank=True, upload_to='salon_foto', verbose_name='Фото'),
        ),
    ]
