# Generated by Django 5.0.7 on 2024-07-29 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0013_salon_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='speciality',
            field=models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Специальность'),
        ),
        migrations.AddField(
            model_name='master',
            name='start_career',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда начал работать'),
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название категории')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_categories', to='salon.service', verbose_name='Услуги')),
            ],
        ),
    ]
