# Generated by Django 5.0.7 on 2024-07-29 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0014_master_speciality_master_start_career_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'категория услуги', 'verbose_name_plural': 'категории услуги'},
        ),
        migrations.AddField(
            model_name='service',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salon.servicecategory', verbose_name='Категория услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название услуги'),
        ),
    ]
