# Generated by Django 5.0.7 on 2024-07-29 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0016_remove_service_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecategory',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='salon.servicecategory', verbose_name='Категория услуги'),
        ),
    ]
