# Generated by Django 5.0.7 on 2024-07-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0017_remove_servicecategory_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='salon',
            field=models.ManyToManyField(blank=True, related_name='salon_categories', to='salon.salon'),
        ),
    ]
